### PR TITLE
Update to Go1.14 & misc changes

### PR DESCRIPTION
**Pull request by elsesiy**
Fix panic due to timestamp type assertion
Add go modules to examples & update dockerfile
Bump version of ugorji/go to 1.1.7
Go format

### CODE REVIEW

**Comment by elsesiy** [comment]
@edsiper @wfernandes Please have a look and let me know if anything is missing from this PR, thanks

**Comment by wfernandes** [comment]
@elsesiy Thanks for this PR!
Most of the changes look good to me. Is it possible to split the work into separate commits? 
And could you also follow the commit message convention, I think that would make it easier for @edsiper to track the changes as well.
For example,
`examples: Fix panic due to timestamp type assertion`
`modules: Bump version of ugorji/go to 1.1.7`
`output: go fmt`

**Comment by edsiper** [comment]
@elsesiy ping

**Comment by elsesiy** [comment]
So how do you want me to separate the changes exactly? 
I’m not familiar with the commit message convention and they seem to differ for the various repos under this org.

**Comment by edsiper** [comment]
as was suggested above:

https://github.com/fluent/fluent-bit-go/pull/31#issuecomment-626794533

**Comment by elsesiy** [comment]
@edsiper My question was related to how fine-grained the commits should be e.g. should be adding a gitignore file a separate commit. Anyway, I split the work in 4 commits now, please have another look and let me know.

**Comment by elsesiy** [comment]
@edsiper @wfernandes Is this still missing anything?

**Comment by elsesiy** [comment]
@edsiper Ping

**Comment by elsesiy** [comment]
@edsiper @PettitWesley Can anybody take a look please?

**Pull request merged**
