### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by svett**
Hi @edsiper,

I am responding to your question by fixing the problem for you. I suggest the following:

1. Keep the C-code in the Golang package wrapper
2. Do not import "C" if you do not need it.

### CODE REVIEW

**Comment by edsiper** [comment]
thanks so much for reviewing this.

What I forgot to mention is that the caller "test.go/main.go" needs to import "C" because it does other stuff not related with the imported "output" package, on that scenario what can be done ?

**Comment by svett** [comment]
Why do not keep any C related logic in wrapper packages and keep main.go Golang agnostic?

**Comment by edsiper** [comment]
It would be ideal, but likely users of this package will need to do their own "C" stuff (not related to the package), the thing is I don't understand why a new import "C" breaks everything. is this a limitation ?

**Comment by svett** [comment]
@edsiper It should work in both cases. I updated the `main.go` to proof that.

**Comment by edsiper** [comment]
thanks @svett. I think the only remaining problem is that it needs to have the export line, e.g:

```
//export my_test
```

this is because the package users will create a shared library, adding the export Go complains about that type cannot be exported

**Comment by svett** [comment]
Hey @edsiper I modified the code for you 😄 enjoy!

**Comment by edsiper** [comment]
thanks so much for your help!

**Pull request merged**
