### PR TITLE
output: make plugin context operations safe for concurrent use

### PR DESCRIPTION
**Pull request by l2dy**
See #45.

### CODE REVIEW

**Comment by nokute78** [comment]
How about using a plane map + RWMutex ?


https://pkg.go.dev/sync#Map

```
The Map type is specialized. Most code should use a plain Go map instead,
 with separate locking or coordination, for better type safety and to make it easier to maintain other invariants along with the map content.

The Map type is optimized for two common use cases:
 (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow,
 or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys.
 In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.
```

**Comment by l2dy** [comment]
Output plugins should be heavy on reading the contexts map, not updating it. If context state update is needed in FLBPluginFlushCtx, store a pointer in context and it will be out of the scope of this sync.Map.

**Comment by l2dy** [comment]
In fact, every time FLBPluginSetContext is called a new key is used, so this is exactly use case (1), a cache that only grows.

**Comment by nokute78** [comment]
OK. 
I understood `FLBPluginSetContext` doesn't support overwriting.
Thank you.

**Comment by l2dy** [comment]
@nokute78 Can you merge this pull request?

**Comment by nokute78** [comment]
@l2dy @edsiper 
Sorry I can't merge since I don't have a permission to merge.

This PR is LGTM.

**Comment by edsiper** [comment]
@nokute78 pls check for permissions now...

**Comment by nokute78** [comment]
Oh I can find "Merge pull request" button now.

**Pull request merged**
