### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
fix Dockerfile typo

### CODE REVIEW

**Comment by ZP-AlwaysWin** [comment]
@PettitWesley  Can you assign someone to review this PR?

**Comment by ZP-AlwaysWin** [comment]
> @PettitWesley Can you assign someone to review this PR?

hi @PettitWesley Excuse me I want to join the fluent community and become a Mermber. What contribution do I need to make to qualify

**Comment by PettitWesley** [comment]
@ZP-AlwaysWin There are different maintainer groups actually; the fluent organization is the parent for all and @edsiper is the lead maintainer for all. 

For Fluent Bit Golang, since it is a smaller project/side-project, rules have not been written down. In my case, I became Fluent Bit go maintainer because I created and maintain two widely used Go plugins ([CloudWatch Logs](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit) and [Kinesis Firehose](https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit)).

For fluent bit core- [the high level requirements have been written down](https://github.com/fluent/fluent-bit/blob/master/GOVERNANCE.md). In my case, I became a maintainer there after I had built a [few](https://github.com/fluent/fluent-bit/pull/1879) [bigger](https://github.com/fluent/fluent-bit/pull/1795) [features](https://github.com/fluent/fluent-bit/pull/2010), and had spent a few months occasionally helping with PR reviews, small fixes, and answering questions in issues.

**Comment by ZP-AlwaysWin** [comment]
> @ZP-AlwaysWin There are different maintainer groups actually; the fluent organization is the parent for all and @edsiper is the lead maintainer for all.
> 
> For Fluent Bit Golang, since it is a smaller project/side-project, rules have not been written down. In my case, I became Fluent Bit go maintainer because I created and maintain two widely used Go plugins ([CloudWatch Logs](https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit) and [Kinesis Firehose](https://github.com/aws/amazon-kinesis-firehose-for-fluent-bit)).
> 
> For fluent bit core- [the high level requirements have been written down](https://github.com/fluent/fluent-bit/blob/master/GOVERNANCE.md). In my case, I became a maintainer there after I had built a [few](https://github.com/fluent/fluent-bit/pull/1879) [bigger](https://github.com/fluent/fluent-bit/pull/1795) [features](https://github.com/fluent/fluent-bit/pull/2010), and had spent a few months occasionally helping with PR reviews, small fixes, and answering questions in issues.

Ok,Thank you very much for your reply. Best Wishes

**Pull request merged**
